name = "arcs-for-mathlib"
version = "1.1.0"
defaultTargets = ["ArcsForMathlib"]

[[lean_lib]]
name = "ArcsForMathlib"


[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#d2ffb33f962f4f8d59e5e80f1ca85150966b49b7"
